### ISSUE TITLE
Getting Undefined Functions Compiling for X86-64

### ISSUE THREAD

**Issue by nmhamster** [Qthreads/qthreads#35] opened 2016-10-04 01:43 UTC
Compiled for KNL using generic X86-64 and I'm getting the following during link:

```
/home/projects/x86-64-knl/qthreads/20161003/lib/libqthread.so: undefined reference to `qt_setmctxt'
/home/projects/x86-64-knl/qthreads/20161003/lib/libqthread.so: undefined reference to `qt_getmctxt'
```

**Comment by npe9** [comment] 2016-10-04 14:57
Can you dump the output of ./configure? It looks like it's not including include/fastcontext/386-ucontext.h correctly, which I suspect is because the KNL is throwing autoconf for a loop.

**Comment by stelleg** [comment] 2016-10-05 15:05
@nmhamster, I'm having trouble reproducing this. With git and the latest release, with both GCC 4.7 and ICC 17.0 I'm compiling and running successfully on KNL. As @npe9 said, more information would be useful and there's likely an issue with the configuration step.

**Comment by nmhamster** [comment] 2016-10-05 15:11
@stelleg are you running on Bowman?

**Comment by stelleg** [comment] 2016-10-05 15:11
@nmhamster yep

**Comment by olivier-snl** [comment] 2016-10-12 06:37
@nmhamster Is this still unresolved?

**Comment by npe9** [comment] 2016-12-02 16:55
@nmhamster Any updates?

**Comment by npe9** [comment] 2017-06-13 16:21
@nmhamster Any updates? If not I'm going to close this issue.

**Closed** 2022-09-08 19:47 UTC
Labels: bug
