### ISSUE TITLE
sinc issues with multiple workers per shepherd on power and arm

### ISSUE THREAD

**Issue by stelleg** [Qthreads/qthreads#57] opened 2018-07-05 17:06 UTC
I'm seeing issues with `sherwood` and `distrib` on power and arm when using sincs and `NUM_WORKERS_PER_SHEPHERD > 1`.

I'm guessing there needs to be some added memory fences. A sinc-based fib exercises the bugs:

```
#include <qthread/qthread.h>
#include <qthread/sinc.h>
#include <assert.h>

typedef struct {
  int i;
  qt_sinc_t* s;
  int *ret;
} args_t;

aligned_t fib(void *args_){
  args_t* args = (args_t*)args_;
  if(args->i < 2){
    *args->ret = 1;
    qt_sinc_submit(args->s, NULL);
    return 0;
  }
  int x, y;
  qt_sinc_t sinc;
  qt_sinc_init(&sinc, 0, NULL, NULL, 2);

  args_t argsx = { args->i-1, &sinc, &x };
  args_t argsy = { args->i-2, &sinc, &y };

  qthread_fork_copyargs(fib, &argsx, sizeof(args_t), NULL);
  qthread_fork_copyargs(fib, &argsy, sizeof(args_t), NULL);

  qt_sinc_wait(&sinc, NULL);
  qt_sinc_submit(args->s, NULL);
  *args->ret  = x + y;
  return 0;
}

int main(){
  assert(qthread_initialize() == 0);
  qt_sinc_t sinc;
  qt_sinc_init(&sinc, 0, NULL, NULL, 1);
  int ret;
  args_t args = { 30, &sinc, &ret };
  qthread_fork_copyargs(fib, &args, sizeof(args_t), NULL);
  qt_sinc_wait(&sinc, NULL);
  printf("%d\n", ret);
}
```

**Comment by stelleg** [comment] 2018-07-05 17:12
Looks like `distrib` can also have  issues even with 1 worker per shepherd. I'm also not convinced it is `sinc`-related, as this errors seem to be occurring in enqueue dequeue subroutines.

**Comment by npe9** [comment] 2018-07-06 17:22
Gotcha, I'll look at this next week.

**Comment by olivier-snl** [comment] 2018-07-09 13:48
@stelleg Thanks for the reproducer, which we might want to add to the test suite.  The timing is good since we are preparing for an end of FY point release, and we can include a fix for this in that.

**Comment by npe9** [comment] 2018-07-09 15:41
@olivier-snl I just added @stelleg's test to the test suite (it passes on OSX). I'll play with it on the testbeds. Do we have a testbed that would be particularly representative?

**Comment by olivier-snl** [comment] 2018-07-09 15:57
@npe9 white for power and mayer for arm

**Comment by npe9** [comment] 2018-07-09 19:21
@stelleg I just tried it on mayer --one of our arm systems. I couldn't reproduce the bug (if I understand it correctly).

```
nevans@mayer:~/src/qthreads.arm/test/basics/.libs$ export QT_NUM_SHEPHERDS=2; export QT_NUM_WORKERS_PER_SHEPHERD=2; ./sinc_workers
1346228
```
where ./sinc_workers is your code above. My configure line is `./configure --with-scheduler=distrib`.

Am I missing something?

**Comment by npe9** [comment] 2018-07-18 21:17
@stelleg Update, I *did* reproduce the bug on white one of our ppc testbeds with distrib.

```
SHEPHERDS=2; export QT_NUM_WORKERS_PER_SHEPHERD=2; ./sinc_workers
<hangs forever>
```

Make check also blew up (actual segfault) in `qt_loop` and `qt_loop_sinc` so our ppc version definitely needs work.

@stelleg Which do you care more about, ppc or arm?

**Comment by npe9** [comment] 2018-07-18 23:34
I isolated at least one of the problems down to threadqueues_distrib.c:275 in `qt_threadqueue_dequeue_tail`.

The code is segfaulting on the dereference of q->tail (via node) which is actually the null pointer.
```
  node = (qt_threadqueue_node_t *)q->tail;
=>  q->tail = node->prev;
  if(q->tail) q->tail->next = NULL;
```
which should not be true because `q->qlength` > 0.

My initial stab at it was to throw a `MACHINE_FENCE` before `qlength` was updated in both the enqueue and the dequeue and to add asserts to make sure that qlength > 1 and a null node was caught.

Turning on asserts now catches most of the segfaults. 

```
nevans@white11:~/src/qthreads.ppc$ export QT_NUM_SHEPHERDS=2; export QT_NUM_WORKERS_PER_SHEPHERD=2; test/basics/.libs/sinc_workers
sinc_workers: threadqueues/distrib_threadqueues.c:278: qt_threadqueue_dequeue_tail: Assertion `q->tail != ((void *)0)' failed.
Aborted
nevans@white11:~/src/qthreads.ppc$ export QT_NUM_SHEPHERDS=2; export QT_NUM_WORKERS_PER_SHEPHERD=2; test/basics/.libs/sinc_workers
sinc_workers: mpool.c:411: qt_mpool_free: Assertion `cnt != 0' failed.
Aborted
nevans@white11:~/src/qthreads.ppc$ export QT_NUM_SHEPHERDS=2; export QT_NUM_WORKERS_PER_SHEPHERD=2; test/basics/.libs/sinc_workers
sinc_workers: qthread.c:2656: qthread_spawn: Assertion `me->rdata' failed.
Segmentation fault
nevans@white11:~/src/qthreads.ppc$ export QT_NUM_SHEPHERDS=2; export QT_NUM_WORKERS_PER_SHEPHERD=2; test/basics/.libs/sinc_workers
sinc_workers: qthread.c:597: qthread_master: Assertion `(t->thread_state == QTHREAD_STATE_NEW) || (t->thread_state == QTHREAD_STATE_RUNNING) || (t->thread_state == QTHREAD_STATE_YIELDED && t->flags & (1 << 1))' failed.
sinc_workers: qthread.c:597: qthread_master: Assertion `(t->thread_state == QTHREAD_STATE_NEW) || (t->thread_state == QTHREAD_STATE_RUNNING) || (t->thread_state == QTHREAD_STATE_YIELDED && t->flags & (1 << 1))' failed.
Aborted
nevans@white11:~/src/qthreads.ppc$ export QT_NUM_SHEPHERDS=2; export QT_NUM_WORKERS_PER_SHEPHERD=2; test/basics/.libs/sinc_workers
sinc_workers: mpool.c:411: qt_mpool_free: Assertion `cnt != 0' failed.
Aborted
nevans@white11:~/src/qthreads.ppc$ export QT_NUM_SHEPHERDS=2; export QT_NUM_WORKERS_PER_SHEPHERD=2; test/basics/.libs/sinc_workers
sinc_workers: qthread.c:597: qthread_master: Assertion `(t->thread_state == QTHREAD_STATE_NEW) || (t->thread_state == QTHREAD_STATE_RUNNING) || (t->thread_state == QTHREAD_STATE_YIELDED && t->flags & (1 << 1))' failed.
sinc_workers: mpool.c:415: qt_mpool_free: Assertion `cnt == 0' failed.
Aborted
``` 

This suggests that there's more corruption than meets the eye. I'll continue to look at it.

**Comment by npe9** [comment] 2018-07-18 23:37
@stelleg I also created a new branch https://github.com/Qthreads/qthreads/tree/mem-issues-ppc where I'm putting my changes. Feel free to check it out and play with it.

**Comment by olivier-snl** [comment] 2018-07-19 13:53
MACHINE_FENCE is heavyweight.  It's okay for starters, but we should take some time to reason about where we could get away with lighter synchronizations in each case.  That will be a big part of resolving these issues with the power and arm architectures.

**Comment by npe9** [comment] 2018-07-19 18:49
@olivier-snl That's fine with me. My main goal is to use it as a hammer to find the races. We can go to a more fine-grained approach from there.

**Comment by npe9** [comment] 2018-07-19 21:52
@olivier-snl @stelleg Update: Having poked at it for a while there seems to be a race between thread termination (and potentially other state changes) and `t = qt_scheduler_get_thread(threadqueue, localqueue, QTHREAD_CASLOCK_READ_UI(me->active));` in `qthread_master()`.

This race only seems to be triggered when QT_NUM_WORKERS_PER_SHEPHERD >1. I can reproduce it in sherwood as well as distrib so I'm pretty sure this is a latent bug in Qthreads proper rather than in distrib.

**Comment by npe9** [comment] 2018-07-20 01:51
@stelleg @olivier-snl Update 2: I just got the various sinc implementations to compile in modern Qthreads. After a few tests that worked using snzi, I'm guessing the bug is in the donecount sinc implementation.

```
nevans@white11:~/src/qthreads.ppc$ ./configure --with-scheduler=distrib --enable-debugging  --enable-asserts --enable-debug=mpool --with-topology=sys --with-sinc=snzi
checking for a BSD-compatible install... ^Cnevans@white11:~/src/qthreads.ppc$ ^C
nevans@white11:~/src/qthreads.ppc$ export QT_NUM_SHEPHERDS=2; export QT_NUM_WORKERS_PER_SHEPHERD=2; test/basics/.libs/sinc_workers
1346274
nevans@white11:~/src/qthreads.ppc$  export QT_NUM_SHEPHERDS=2; export QT_NUM_WORKERS_PER_SHEPHERD=2; test/basics/.libs/sinc_workers
1346273
```

**Comment by npe9** [comment] 2018-07-20 01:54
@olivier-snl I also pushed the sinc updates into master which might be something to report when we do a release.

**Comment by olivier-snl** [comment] 2018-07-23 13:53
Thanks @npe9 .  Let's meet some time this week to discuss where things stand.

**Comment by stelleg** [comment] 2018-07-30 16:18
@npe9 I'm seeing similar nondeterministic behavior with the above code, with no more seg faults. Progress!

Unfortunately, in the initial code I left out a `qt_sinc_fini(&sinc)` after the `qt_sinc_wait(&sinc)`, which needs to be there to prevent memory leaks, and with it inserted I'm seeing nondeterministic bus errors, at least on arm:

```
QTHREADS: Using 2 Shepherds
QTHREADS: Using 128 Workers per Shepherd
QTHREADS: Using 4096 byte stack size.
Bus error (core dumped)
```

`gdb` is pointing to the error occurring at `feb.c:1245`, though I admit it's not obvious to me why the error is occurring. Maybe an issue with the arm FASTLOCK implementation?

**Comment by npe9** [comment] 2018-07-30 16:57
@stelleg which sinc implementation are you using now? snzi? Also what kind of arm are you running on? I can get PPC to reproduce your errors, but nothing on the arm testbed so far.

**Comment by stelleg** [comment] 2018-07-30 18:24
@npe9 seeing the issue on both `donecount` and `snzi`. With the addition of the `qt_sinc_fini(&sinc)` call, I will sometimes get bus errors, sometimes get wrong answers, and sometimes get hanging.

**Comment by npe9** [comment] 2018-07-31 16:45
@stelleg Gotcha, can you give me the exact arm you're running on? Also have you seen the same behavior on PPC?

**Comment by stelleg** [comment] 2018-08-23 14:34
ARM cpu is a 64 core Thunder X2, and yes I'm seeing the issues on Power9 as well.

**Comment by npe9** [comment] 2018-09-13 19:48
@stelleg what compiler are you using?

**Comment by ronawho** [comment] 2018-09-13 22:28
FYI we're also seeing possible qthread bugs on ARM (also 64-core thunderx2.) We're on a Cray with PrgEnv-gnu (gcc 7.3)

https://github.com/chapel-lang/chapel/issues/10840
https://github.com/chapel-lang/chapel/issues/11106

I don't have anything concrete to add here yet, but if we discover something useful I'll let you know.

**Comment by npe9** [comment] 2018-09-13 22:38
@ronawho That's really helpful thanks. That potentially narrows the bug to libc or FEB interactions as well as sinc (they could just as easily be a separate problem though).

**Comment by janciesko** [comment] 2020-12-10 21:01
@npe9 since you mentioned sinc, this might be related to https://github.com/Qthreads/qthreads/issues/59. It seems that sinc_workers is causing a hang when make check -j4. My understanding is that the branch https://github.com/Qthreads/qthreads/tree/mem-issues-ppc does not fix the issue yet.

**Comment by janciesko** [comment] 2021-02-20 03:09
@ronawho  - Elliot, this is still relevant as I can reproduce the problem with our master. I am putting this on high priority as this might cause our CI test run hangs and hangs in related projects.

**Comment by janciesko** [comment] 2021-11-23 04:14
[PR 98 ](https://github.com/Qthreads/qthreads/pull/98) likely fixes the issue. Please confirm if possible.

**Comment by olivier-snl** [comment] 2021-11-30 22:43
@stelleg : @janciesko has combined the recent work by himself and @cjhackillinois at this branch: https://github.com/Qthreads/qthreads/tree/PRTestBranchNov2021

Could you give that branch a try on your side when you get a chance?

**Comment by cjhackillinois** [comment] 2021-12-01 20:54
I moved over to the PR branch on ARMv8.
These are the steps I took
`git checkout PRTestBranchNov2021`
`make distclean`
![image](https://user-images.githubusercontent.com/47911162/144312228-936f9ee5-8f5a-4eaa-8359-c624211cf9c2.png)

`make -j`
`make check -j4`

![image](https://user-images.githubusercontent.com/47911162/144312371-a5a9ef74-bfae-418a-afd0-42b232933893.png)

**Comment by cjhackillinois** [comment] 2021-12-01 21:03
Some different settings:

![image](https://user-images.githubusercontent.com/47911162/144313371-b9879227-f501-4cd0-a4b6-03daf0245dbe.png)

`make`

Looks like we need to add assembly for Aarch64
![image](https://user-images.githubusercontent.com/47911162/144313501-684d49ee-e8ba-43fb-b163-ce4af45a274c.png)

**Comment by olivier-snl** [comment] 2021-12-01 21:07
Yes, we knew that those were missing.  The working options are the compiler built-ins (default) and the slower pthreads mutex option (which is mainly there for portability).  @janciesko and I speculate that the assembly-based may not be that much faster than the built-ins, so we're pondering whether they can be put off.

**Comment by cjhackillinois** [comment] 2021-12-01 21:34
So I ran configure with both settings (not sure if this is correct).

![image](https://user-images.githubusercontent.com/47911162/144317645-0311df33-60ad-441d-9e8f-b383ebb6ac65.png)


If I run `make check` it works. However, if I run `make check -j4` it seems to mostly fail (not 100%) on the qutil test

![image](https://user-images.githubusercontent.com/47911162/144317592-44e4cdb7-0c3e-48da-bae3-66ff5f0cef85.png)

**Comment by cjhackillinois** [comment] 2021-12-01 21:57
@olivier-snl I agree with the assembly. It may not be worth the effort. However, some may ask why have assembly for some architectures and not others?

**Comment by dmk42** [comment] 2021-12-01 22:05
@cjhackillinois - A good reason for that is that C11 is much more widely available now than it was before, so it is now OK to lean on that.  That is a debate Chapel went through as well.

Full disclosure - I'm the convener of the ISO C standards committee.

**Comment by cjhackillinois** [comment] 2021-12-01 22:24
@dmk42 Thanks for the feedback. Do you know of any research or publication which compares synchronization primitives on ARMv8? In particular, these comparisons:

- Assembly
- Compiler intrinsics
- Pthread POSIX

**Comment by dmk42** [comment] 2021-12-01 22:32
Sorry, I don't know of any direct comparisons.

I would expect the compiler intrinsics normally to be faster than the alternatives, for the reason that the optimizer has the opportunity to take them into account, which it can't do with the other options.  There might be isolated cases where it comes out slightly behind assembly, if there is an object that should usually be accessed atomically but goes through phases where it can be accessed nonatomically.  The compiler will not pick up the nonatomic cases and will always use the atomic instrucitons, unless someone explicitly uses atomic_init() which is meant for nonatomic initialization of atomic objects.

**Comment by cjhackillinois** [comment] 2021-12-01 22:38
@olivier-snl @janciesko  
I switched back to:
![image](https://user-images.githubusercontent.com/47911162/144325266-ca36e0d6-eda4-4010-86d8-a59810b012b7.png)

And running `make check -j4` still has some issues (not sure):

![image](https://user-images.githubusercontent.com/47911162/144325487-f0788e65-7bb6-4f3b-9f1e-6b08b481313f.png)

**Comment by olivier-snl** [comment] 2021-12-01 22:38
> Sorry, I don't know of any direct comparisons.
> 
> I would expect the compiler intrinsics normally to be faster than the alternatives, for the reason that the optimizer has the opportunity to take them into account, which it can't do with the other options. There might be isolated cases where it comes out slightly behind assembly, if there is an object that should usually be accessed atomically but goes through phases where it can be accessed nonatomically. The compiler will not pick up the nonatomic cases and will always use the atomic instrucitons, unless someone explicitly uses atomic_init() which is meant for nonatomic initialization of atomic objects.

My expectation is similar: assembly > intrinsics >> pthreads mutex in terms of efficiency.  @janciesko and I had talked about doing a study, in case it is of interest to others.

The point about wider C11 availability is also valid.  The original Qthreads paper is from 2008 in fact.

**Comment by cjhackillinois** [comment] 2021-12-02 00:03
![image](https://user-images.githubusercontent.com/47911162/144333722-33584f40-65ca-4c33-a924-709a9e02689d.png)


I did a basic configure and not the `make check -j4` fails at the same test:

![image](https://user-images.githubusercontent.com/47911162/144333494-b153d22b-b1fe-4d99-b758-ea99c37d41bb.png)

**Closed** 2022-01-10 16:07 UTC
Labels: bug, high priority
